### ISSUE TITLE
Support pre-releases

### ISSUE THREAD

**Issue by hugovk** [glyph/MOPUp#308]
I have 3.13.0a5 and would like to use MOPUp to install the latest 3.13.0a6: https://www.python.org/download/pre-releases/

```console
❯ python3.13 --version
Python 3.13.0a5
```

But it's not finding any `versions` for pre-releases:

```pytb
❯ python3.13 -m mopup
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mopup/__main__.py", line 36, in <module>
    main(prog_name="mopup")  # pragma: no cover
    ~~~~^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ~~~~~~~~~~~^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mopup/__main__.py", line 32, in main
    libmain(interactive=interactive, force=force, minor_upgrade=minor, dry_run=dry_run)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mopup/__init__.py", line 66, in main
    newminor = max(versions[thismajor].keys())
               ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```

**Comment by glyph** [comment]
@hugovk thanks for the bug report. I haven't tested with prereleases yet, I should probably do that :)

**Comment by glyph** [comment]
OK, I think that trunk should work for prereleases now. If it works for you I can do a release.

**Comment by glyph** [comment]
On my own system:

```
this version: 3.13.0a5; new version: 3.13.0a6
update needed from https://www.python.org/ftp/python/3.13.0/python-3.13.0a6-macos11.pkg
Downloading python-3.13.0a6-macos11.pkg... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
.
Enter your administrative password to run the update:
Password:
installer: Package name is Python
installer: Upgrading at base path /
installer: The upgrade was successful.
Complete.
```

**Comment by hugovk** [comment]
Success, thanks!

```console
❯ python3.13 -m pip install git+https://github.com/glyph/MOPUp
...
❯ python3.13 -m mopup
this version: 3.13.0a5; new version: 3.13.0a6
update needed from https://www.python.org/ftp/python/3.13.0/python-3.13.0a6-macos11.pkg
Downloading python-3.13.0a6-macos11.pkg... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
.
Enter your administrative password to run the update:
Password:
installer: Package name is Python
installer: Upgrading at base path /
installer: The upgrade was successful.
Complete.

❯ python3.13 --version
Python 3.13.0a6
```

**Comment by glyph** [comment]
OK, great. Seems like it still picks up final releases OK too. I should probably have more unit tests about this :)

**Comment by glyph** [comment]
2024.04.12 is out now, and supports prereleases.

**Comment by hugovk** [comment]
Thank you! :rocket:
