### ISSUE TITLE
Also upgrade free-threaded Python if installed

### ISSUE THREAD

**Issue by hugovk** [glyph/MOPUp#346]
It would be nice if MOPUp also upgraded the free-threaded Python, `python3.13t`.

1. Install Python 3.13.0b4 with the [official installer](https://www.python.org/downloads/release/python-3130b4/)
2. When prompted, click Customise:
![image](https://github.com/user-attachments/assets/1a74ccaa-8ee4-4577-88f5-d5404af8f164)
3. Check to install "Free-threaded Python [experimental]":
![image](https://github.com/user-attachments/assets/29a41112-ab24-4134-99ae-04fa6be4be7d)
4. Complete the install
5. Check versions of regular Python and free-threaded (with `t`):
```console
❯ python3.13 --version
Python 3.13.0b4

❯ python3.13t --version
Python 3.13.0b4
```

6. Use MOPUp to upgrade from b4 to rc1:
```console
❯ python3.13 -m mopup
this version: 3.13.0b4; new version: 3.13.0rc1
update needed from https://www.python.org/ftp/python/3.13.0/python-3.13.0rc1-macos11.pkg
Downloading python-3.13.0rc1-macos11.pkg... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
.
Enter your administrative password to run the update:
Password:
installer: Package name is Python
installer: Upgrading at base path /
installer: The upgrade was successful.
Complete.
```
7. Check versions:

Actual result: `python3.13t` isn't upgraded:
```console
❯ python3.13 --version
Python 3.13.0rc1

❯ python3.13t --version
Python 3.13.0b4
```

Expected result: `python3.13t` is also upgraded to rc1:

```console
❯ python3.13 --version
Python 3.13.0rc1

❯ python3.13t --version
Python 3.13.0rc1
```

**Comment by glyph** [comment]
This is definitely something I'd like to see! Free-threading (obviously) postdates MOPUp.

Really the issue here is that we don't support *any* installation options (GUI programs, etc) it's just that the other things default to 'on' whereas freethreading defaults to 'off'.

If I am understanding the structure of the build here, we would need to build some "choice changes XML" and use `installer`'s `-applyChoiceChangesXML` option to turn on the freethreading installation.

**Comment by glyph** [comment]
OK, I implemented it. https://pypi.org/project/MOPUp/2024.8.9/

**Comment by hugovk** [comment]
Thanks! Although I get `FileNotFoundError: [Errno 2] No such file or directory: '/usr/sbin/pkngutil'`:

```pytb
❯ python3.13 -m mopup
this version: 3.13.0b4; new version: 3.13.0rc1
update needed from https://www.python.org/ftp/python/3.13.0/python-3.13.0rc1-macos11.pkg
Downloading python-3.13.0rc1-macos11.pkg... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mopup/__main__.py", line 37, in <module>
    main(prog_name="mopup")  # pragma: no cover
    ~~~~^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mopup/__main__.py", line 33, in main
    libmain(interactive=interactive, force=force, minor_upgrade=minor, dry_run=dry_run)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mopup/__init__.py", line 159, in main
    tf.write(choicechanges(finalname))
             ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mopup/__init__.py", line 43, in choicechanges
    run(  # noqa: S603
    ~~~^^^^^^^^^^^^^^^
        [
        ^
    ...<3 lines>...
        stdout=PIPE,
        ^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1966, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/sbin/pkngutil'
```
And indeed I don't have `/usr/sbin/pkngutil`

`which pkngutil` and `locate pkngutil` have no results.

I'm on macOS Sonoma 14.6.

**Comment by hugovk** [comment]
I do however have `/usr/sbin/pkgutil` (no `n`), and it works with this. Please see PR https://github.com/glyph/MOPUp/pull/352.
