### ISSUE TITLE
Idea: notify if source release updates are available

### ISSUE THREAD

**Issue by wimglenn** [glyph/MOPUp#386]
Once a branch is in security release only, there are still python.org releases but not binary installers, e.g.

- Binary: https://www.python.org/downloads/release/python-3119/
- Source only: https://www.python.org/downloads/release/python-31110/

Even if it can't install them, I think it would be nice for MOPUp to print some message or notify when newer source updates are _available_.

The current output is a little confusing, calling the latest binary the "new" version, e.g.

```bash
this version: 3.11.10; new version: 3.11.9
update not needed from https://www.python.org/ftp/python/3.11.9/python-3.11.9-macos11.pkg
```

**Comment by glyph** [comment]
Yes, this is a shortcoming that a few people have pointed out. Given that MOPUp is primarily a security helper tool, and security releases are for some reason released as source-only, this is a gap that should be addressed.

I might even go so far as to say that the build environment probably isn't *that* hard to replicate, so it might even be worth doing a best-effort build of a `.pkg` to install.

Unfortunately https://devguide.python.org/getting-started/setup-building/ doesn't provide instructions for building with parity with the official installers, and I'm not quite sure how to reverse-engineer the contents of `/Library/Frameworks/Python.framework/Versions/X.Y/lib/pythonX.Y/config-X.Y-darwin/` into a set of arguments to pass to `./configure` in a source checkout.  If we can figure that out, we can substitute in that build line for the `installer` invocation.

**Comment by glyph** [comment]
(Or, I dunno, is there a github actions thing in CPython somewhere? I know surprisingly little about building CPython!)

**Comment by glyph** [comment]
Oh wait, here we go: https://github.com/python/cpython/blob/34653bba644aa5481613f398153757d7357e39ea/Mac/BuildScript/build-installer.py

**Comment by glyph** [comment]
Hmm. Okay this script is *very* much not intended for downstream consumption. I had to do `mkdir -p ~/Universal/other-sources` before it would even attempt to work.  I wonder if it might make sense to just set up an Actions builder on *this* project to just attempt to mirror the official releases as closely as possible.

**Comment by glyph** [comment]
Sigh. In my test after making that directory, it got about this far:

```
Did not find local copy of ncurses-5.9-20120616-patch.sh.bz2
Downloading ncurses-5.9-20120616-patch.sh.bz2
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1541, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1561, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
                      persistent=False)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 2394, in __init__
    self.init()
    ~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 2404, in init
    self.ftp.login(self.user, self.passwd)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ftplib.py", line 414, in login
    resp = self.sendcmd('PASS ' + passwd)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ftplib.py", line 281, in sendcmd
    return self.getresp()
           ~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ftplib.py", line 254, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 Login incorrect.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/glyph/Projects/CPython/Mac/BuildScript/build-installer.py", line 1778, in <module>
    main()
    ~~~~^^
  File "/Users/glyph/Projects/CPython/Mac/BuildScript/build-installer.py", line 1728, in main
    buildLibraries()
    ~~~~~~~~~~~~~~^^
  File "/Users/glyph/Projects/CPython/Mac/BuildScript/build-installer.py", line 1085, in buildLibraries
    buildRecipe(recipe, universal, ARCHLIST)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glyph/Projects/CPython/Mac/BuildScript/build-installer.py", line 998, in buildRecipe
    verifyThirdPartyFile(url, checksum, fn)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/glyph/Projects/CPython/Mac/BuildScript/build-installer.py", line 807, in verifyThirdPartyFile
    downloadURL(url, fname)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/glyph/Projects/CPython/Mac/BuildScript/build-installer.py", line 781, in downloadURL
    fpIn = urllib_request.urlopen(url)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 489, in open
    response = self._open(req, data)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 506, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
                              '_open', req)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1558, in ftp_open
    raise URLError(exp) from exp
urllib.error.URLError: <urlopen error 530 Login incorrect.>
```

Not sure what that's about but not a promising start.

**Comment by hynek** [comment]
I don't want to tag them, but maybe talk to CPython release managers and see if they'd be open to a… as the kids say …collab?
